name: "Infra CI"

on:
  push:
    paths:
      - 'infra/**'



permissions:
  id-token: write
  contents: read

jobs:
  aws-assume:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: "TestFedRole"
      - name: Assume deploy role AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_TEST_ROLE_ARN }}
          role-session-name: "TestFedRole"
          role-chaining: true
    
        
      - name: Install Infra dependencies
        working-directory: infra
        run: npm install

      - name: Install CDKTF
        run: npm install --global cdktf-cli@latest

      - name: CDKTF Get
        working-directory: infra
        run: cdktf get --no-color
       
      - name: Deploy Backend
        uses: hashicorp/terraform-cdk-action@v11
        with:
          cdktfVersion: 0.21.0
          terraformVersion: 1.13.5
          workingDirectory: ./infra
          mode: auto-approve-apply
          stackName: backend
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Backend
        uses: hashicorp/terraform-cdk-action@v11
        with:
          cdktfVersion: 0.21.0
          terraformVersion: 1.13.5
          workingDirectory: ./infra
          mode: auto-approve-apply
          stackName: frontend
          githubToken: ${{ secrets.GITHUB_TOKEN }}
