name: Infra Deploy

on:
  workflow_run:
    workflows: ["Infra Build"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download CDKTF output artifact
        uses: actions/download-artifact@v3
        with:
          name: cdktf-out
          path: infra/cdktf.out

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: "InfraDeploy"

      - name: Assume deploy role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_TEST_ROLE_ARN }}
          role-session-name: "InfraDeploy"
          role-chaining: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli@latest

      - name: CDKTF Deploy
        working-directory: infra
        run: cdktf deploy --auto-approve