name: Infra CI

on:
  push:
    paths:
      - 'infra/**'
      - 'src/**'
  pull_request:
    paths:
      - 'infra/**'
      - 'src/**'

permissions:
  contents: read
  id-token: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Install Infra dependencies
        run: npm install --prefix infra

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli@latest

      - name: CDKTF Get
        working-directory: infra
        run: cdktf get

      - name: CDKTF Synthesize
        working-directory: infra
        run: cdktf synth

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.1
        with:
          version: latest  

      - name: Trivy FS Scan (Application / src)
        run: |
          echo "=== Trivy FS Scan ==="
          trivy config infra/cdktf.out \
          --severity CRITICAL,HIGH \
          --format table \
          --exit-code 1 \
          --quiet

      - name: Trivy IaC Scan (CDKTF output)
        run: |
          echo "=== Trivy IaC Scan ==="
          trivy config infra/cdktf.out \
            --severity CRITICAL,HIGH \
            --format table \
            --exit-code 1 \
            --no-progress

  build:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Install Infra dependencies
        run: npm install --prefix infra

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli@latest

      - name: CDKTF Get
        working-directory: infra
        run: cdktf get

      - name: CDKTF Synthesize
        working-directory: infra
        run: cdktf synth

      - name: Upload CDKTF output
        uses: actions/upload-artifact@v4
        with:
          name: cdktf-out
          path: infra/cdktf.out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Set environment variables
        run: |
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_ENV
          echo "PROFILEINFO=${{ secrets.PROFILEINFO }}" >> $GITHUB_ENV

      - name: Install Infra dependencies
        run: npm install --prefix infra

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli@latest

      - name: Assume main role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: InfraDeploy

      - name: Chain deploy role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_TEST_ROLE_ARN }}
          role-session-name: InfraDeploy
          role-chaining: true

      - name: CDKTF Get
        working-directory: infra
        run: cdktf get

      - name: Deploy Backend + Frontend
        uses: hashicorp/terraform-cdk-action@v11
        with:
          cdktfVersion: 0.21.0
          terraformVersion: 1.13.5
          workingDirectory: ./infra
          mode: auto-approve-apply
          stackName: "backend frontend"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
